name: safety_card_web
description: A Flutter web app for Safety Cards using Drift (web) with prefilled tables.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.18.0
  sqlite3: ^2.4.4
  path: ^1.9.0
  image_picker: ^1.1.1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  collection: ^1.18.0
  sqlite3_flutter_libs: ^0.5.24
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  uuid: ^4.0.0
  http_parser: ^4.1.2
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - web/sqlite3.wasm
    - web/drift_worker.js
    - assets/icons/
